default_options: &default_options
  consistency: :strong
  safe: true

development:
  sessions:
    default:
      database: fg_development
      hosts:
        - localhost:27017
      options:
         <<: *default_options
test:
  sessions:
    default:
      database: fg_test
      hosts:
        - localhost:27017
      options:
        <<: *default_options
